---
- name: Print EC2 Yoram
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: EC2 information
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": Yoram
      register: ec2_info

    - name: Print tags
      debug:
        msg: "Instance ID: {{ item.instance_id }}, Tags: {{ item.tags }}"
      loop: "{{ ec2_info.instances }}"
      when: item.tags is defined
